
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LocalUser
 */
public class ÕÓ‚˚ÈJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ÕÓ‚˚ÈJFrame
     */
    public ÕÓ‚˚ÈJFrame() {
        initComponents();
        lblBalance.setText(String.valueOf(balance));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblDigit1 = new javax.swing.JLabel();
        lblDigit3 = new javax.swing.JLabel();
        lblDigit2 = new javax.swing.JLabel();
        btnAddMoney = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lucky 7");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("¡‡Î‡ÌÒ:");

        lblBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBalance.setText("jLabel2");

        lblDigit1.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        lblDigit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigit1.setText("0");
        lblDigit1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.red));

        lblDigit3.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        lblDigit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigit3.setText("0");
        lblDigit3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.red));

        lblDigit2.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        lblDigit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigit2.setText("0");
        lblDigit2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.red));

        btnAddMoney.setBackground(new java.awt.Color(0, 204, 51));
        btnAddMoney.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddMoney.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMoney.setText("ÔÓÔÓÎÌËÚ¸ ·‡Î‡ÌÒ");
        btnAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoneyActionPerformed(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(255, 51, 51));
        btnPlay.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 0));
        btnPlay.setText("ÒÚ‡Ú");
        btnPlay.setBorder(null);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddMoney))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDigit3)
                    .addComponent(lblDigit2)
                    .addComponent(lblDigit1))
                .addGap(18, 18, 18)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int balance = 100;
    
    private void btnAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoneyActionPerformed
      addMoney frm = new addMoney();  
      frm.setVisible(true);
      
      balance+=frm.amount;
      lblBalance.setText(String.valueOf(balance));
      
    }//GEN-LAST:event_btnAddMoneyActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if(balance-10<0)
        {
            JOptionPane.showMessageDialog(this, "ÕÂ‰ÓÒÚ‡ÚÓ˜ÌÓ ÒÂ‰ÒÚ‚");
        return;
        }
        
        balance-=10;
        
        Random rnd = new Random();
        
        lblDigit1.setText(String.valueOf(rnd.nextInt(10)));
        lblDigit2.setText(String.valueOf(rnd.nextInt(10)));
        lblDigit3.setText(String.valueOf(rnd.nextInt(10)));
        
        int count = 0;
        
        if (lblDigit1.getText().equals("7"))
            count++;
        if (lblDigit2.getText().equals("7"))
            count++;
        if (lblDigit3.getText().equals("7"))
            count++;
        
        if (count!=0)
            balance += (int)Math.pow(10, count);
        
        lblBalance.setText(String.valueOf(balance));
        
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÕÓ‚˚ÈJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÕÓ‚˚ÈJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÕÓ‚˚ÈJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÕÓ‚˚ÈJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÕÓ‚˚ÈJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoney;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblDigit1;
    private javax.swing.JLabel lblDigit2;
    private javax.swing.JLabel lblDigit3;
    // End of variables declaration//GEN-END:variables
}
